import React from 'react'
import type { Metadata } from "next";
import UserProfile from '@/app/components/UserProfile';

export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className="flex flex-col justify-center items-center py-10">
      <UserProfile />
    </div>
  )
}

export default page